version: '3'

services: 
  node:
    image: luizvbneto:node
    build: .
    depends_on: 
      - db
    ports:
      - 5000:5000
    volumes:
      - type: bind
        source: ./application
        target: /application
 
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres
    ports:
      - 25060:5432